spring:
  application:
    name: gridpulse-api
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/gridpulse}
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=300s

server:
  port: 8080

logging:
  level:
    com.gridpulse: DEBUG
